version: "3"
services:
  memcached:
    image: memcached:1.4
    container_name: memcached
    ports:
      - "11211:11211"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:2.6.10
    container_name: "mongo"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    depends_on:
    - memcached
    - mongodb
    - rabbitmq
    image: mutantes
    ports:
    - 8080:8080
    links:
    - mongodb